### ISSUE TITLE
ERROR Was unable to open the browser "phantomjs:"

### ISSUE THREAD

**Issue by darlanmendonca** [DevExpress/testcafe-browser-provider-phantomjs#6] opened 2016-10-21 13:26 UTC
I install testcafe-browser-provider-phantomjs locally with

``` sh
npm i --save-dev testcafe-browser-provider-phantomjs
```

and try run my specs in phantomjs with

``` sh
testcafe phantomjs path/to/my/spec.js
```

but I have this error:

```
ERROR Was unable to open the browser "phantomjs:" due to error.

Cannot read property 'createPage' of null
```

Running in macOS 10.12

Any idea?

**Comment by AndreyBelym** [comment] 2016-10-21 13:30
Hi, what node version are you using?

**Comment by darlanmendonca** [comment] 2016-10-21 13:32
Hi @AndreyBelym

I'm using v6.8.0

**Comment by AndreyBelym** [comment] 2016-10-21 13:44
Cannot reproduce on our OS X 10.11, give me some time, please. Likely it's a bug of https://www.npmjs.com/package/phantom.

**Comment by darlanmendonca** [comment] 2016-10-21 13:46
sure, thanks man :D

**Comment by AndreyBelym** [comment] 2016-10-21 14:01
While we are upgrading our Mac, can you try to download and install this: https://github.com/DevExpress/testcafe-browser-provider-phantomjs/releases/download/v1.0.0-7825c56/testcafe-browser-provider-phantomjs-1.0.0.tgz, run your spec and provide me the output, please?

**Comment by ghost** [comment] 2017-01-20 11:42
I have the same issue, here's the tail of my log:

```
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0] VariableDeclarator: enter
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0] VariableDeclarator: Recursing into...
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].id Identifier: enter
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].id Identifier: Recursing into...
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].id Identifier: exit
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].init CallExpression: enter
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].init CallExpression: Recursing into...
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].init.callee Identifier: enter
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].init.callee Identifier: Recursing into...
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].init.callee Identifier: exit
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].init.arguments[0] Identifier: enter
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].init.arguments[0] Identifier: Recursing into...
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].init.arguments[0] Identifier: exit
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0].init CallExpression: exit
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7].declarations[0] VariableDeclarator: exit
Fri, 20 Jan 2017 11:40:21 GMT babel program.body[7] VariableDeclaration: exit
Fri, 20 Jan 2017 11:40:21 GMT babel [BABEL] /home/redacted/w/redacted/testcafe/tests/google-com.js: End transform traverse
Fri, 20 Jan 2017 11:40:21 GMT babel [BABEL] /home/redacted/w/redacted/testcafe/tests/google-com.js: Generation start
Fri, 20 Jan 2017 11:40:21 GMT babel [BABEL] /home/redacted/w/redacted/testcafe/tests/google-com.js: Generation end
ERROR Was unable to open the browser "phantomjs:" due to error.

Cannot call method 'createPage' of null

Type "testcafe -h" for help.
```

It started with about 5800 lines of babel messages so I cut those off.

**Comment by AndreyBelym** [comment] 2017-01-23 08:26
Hello @WillemMali! What version are you using? Please note, that 'phantom' doesn't support node below `0.12`.

**Comment by AndreyBelym** [comment] 2019-02-11 09:53
I close this issue due to the project is discontinued for about 2 years. If you still use this provider, please consider using alternatives like [Chrome Headless](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/testing-in-headless-mode.html) and https://www.npmjs.com/package/testcafe-browser-provider-nightmare.

**Closed as completed by AndreyBelym** 2019-02-11 09:53 UTC
Labels: STATE: Need response
